### ISSUE TITLE
chore: Remove numpy dependency

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#918]
You can use Hamilton without numpy so there's no reason to have it as a dependency.

By searching `numpy` in `hamilton/**.py`, there are 3 results:
- `hamilton/base.py` where `NumpyMatrixResult` is defined. This could be moved to the `hamilton/plugins/h_numpy.py`. We would need to solve the import pattern.
- `hamilton/telemetry.py` there's a check for the `base.NumpyMatrixBuilder`. We can probably just remove or stitch with the above change?
- `hamilton/log_setup.py` where `np.seterr` is used to ignore some numpy error. This should be safe to delete?

By searchin `numpy` in `tests/**.py` there are more results. Numpy is used to test the 3 previous elements, but also as an input for certain tests and for `@check_output` stuff.
- The easy fix is to keep numpy in the test dependencies.
- We could move certain tests to `tests/plugins/test_h_numpy.py`

Also, we would have to make sure that the examples have an explicit dependency on numpy if they are using it.

**Comment by radujica** [comment]
looks like the same could be said about pandas? it does pop up in more places, but none look core

**Comment by elijahbenizzy** [comment]
> looks like the same could be said about pandas? it does pop up in more places, but none look core

Yes! It's only left there for legacy reasons. One thing I've been meaning to do is add a `hamilton[raw]` that doesn't install it or numpy. The library should have zero dependencies. That's dependent on this.

**Comment by Dev-iL** [comment]
## Tentative work plan

~~~md
# Definition: Hamilton 1.9x transitional rung — pandas/numpy decoupling preparation (apache/hamilton#918)

## 1. Intent & Context

- **Goal:** Land every preparatory, non-breaking change on the 1.x line so that Hamilton 2.0 can remove pandas/numpy from core dependencies as a near-pure deletion changeset. Pandas and numpy REMAIN hard dependencies in this release; nothing observable breaks for any existing user.
- **Mental Model:** The agreed 2.0 ladder (see memory `no-pandas-2-0-ladder.md` and apache/hamilton#918): 1.9x relocates pandas/numpy-coupled classes to the plugins namespace behind deprecation shims, warns on the legacy implicit pandas default, and installs a Django-style version-named deprecation mechanism (`RemovedInHamilton2Warning`) so that 2.0's removal work is grep-driven and CI-enforced. The 2.0 rung (dependency removal, shim deletion, `DictResult` default flip, minimal-install CI job) is explicitly OUT of scope.
- **Repo:** a new worktree (branch `no_pandas`, upstream `apache` = apache/hamilton, PR target `apache/hamilton:main`).

## 2. Approach

*Initial direction, not rigid plan. Expect adjustment when reality diverges.*

- **Architecture:** Six deliverables on one branch, one commit (or small commit group) per deliverable, culminating in a single upstream PR. D1 is the user's "Step 0" cleanup commit (safe deletions/lazy imports, no structure change). D2 builds the central deprecation mechanism every later deliverable consumes. D3 relocates result builders/adapters to `hamilton/plugins/h_pandas.py` (exists, gains the builders) and `hamilton/plugins/h_numpy.py` (new), leaving PEP 562 `__getattr__` shims in `hamilton.base` that emit `RemovedInHamilton2Warning` on attribute access (import of `hamilton.base` itself stays warning-free). D4 adds the implicit-default deprecation warnings in `Driver`/`AsyncDriver`. D5 splits pandas validators out of `data_quality/default_validators.py` with conditional registration mirroring the existing pandera pattern (default_validators.py:512). D6 opens and tends the upstream PR.
- **Execution Order:**
  - D1 → D2 → D3 → D4 → D5 → D6
  - Rationale: D1 first per the user's Step-0 rule (cleanup committed separately before structural refactor of >300 LOC files like base.py). D2 before D3/D4/D5 because they all emit `RemovedInHamilton2Warning` through D2's helper. D6 last — the PR carries all commits.
- **Risk Areas:**
  - [R-1] Warnings-as-errors for internal code floods the existing suite: many tests construct legacy `Driver(config, module)` without a result builder, which D4 makes warn. | Detect: mass pytest failures after D4. | Mitigation locked in T-2: update tests to pass explicit result builders.
  - [R-2] `TYPE_CHECKING`-only pandas imports can break runtime type-hint introspection (`typing.get_type_hints`) on annotations like `models.py` `predict(**inputs: pd.Series)` — Hamilton introspects hints at runtime. | Detect: suite failures; add a targeted introspection test for any module converted to `TYPE_CHECKING` imports whose annotations are runtime-resolved.
  - [R-3] Module `__getattr__` shims are invisible to `dir()`, autodoc, and some static tooling. | Detect: Sphinx docs build, suite. | Mitigation: implement `__dir__` alongside `__getattr__`.
  - [R-4] Re-parenting `SimplePythonGraphAdapter`/`DefaultAdapter` off `PandasDataFrameResult` flips `isinstance`/`issubclass` results. Public GitHub code search (2026-06-12) found no third-party reliance; private code is uncovered. | Detect: not detectable pre-merge; accepted residual risk, called out in changelog.
  - [R-5] Plugin modules (`h_dask.py`, `h_narwhals.py`, `h_spark.py`, `h_vaex.py`, `h_polars.py`) and `async_driver.py` import the relocated names from `base` — they must keep working. | Detect: suite + grep for all consumers (per user CLAUDE.md rule 10: search direct refs, type refs, string literals, dynamic imports, re-exports, tests/mocks separately).
- **Trade-offs:**
  - [T-1] Backward-compat completeness vs clean 2.0 → Prefer shims + warnings on every moved/changed public name now, hard removal at 2.0, because the dependency break should be the only break users feel and import paths migrate via warnings.
  - [T-2] Updating existing tests to explicit result builders vs suppressing the new warning in tests → Prefer explicit builders, because it leaves the test suite already valid for 2.0 and exercises the migration path users will follow.
  - [T-3] One PR with per-deliverable commits vs multiple PRs → Prefer one PR, because the deliverables are interdependent (D2's mechanism is consumed by D3–D5), upstream review gets one coherent narrative tied to #918, and the devlist discussion references a single artifact.

## 3. Global Invariants

*Rules that apply to the ENTIRE execution. If these fail, the task fails.*

- [INV-G1] Full test suite passes in the worktree.
  ```yaml
  verify:
    prompt: |
      In the worktree run: uv sync --group test && uv run pytest tests/ --ignore tests/integrations
      PASS only if the suite exits 0. FAIL with the failing test names and output excerpts otherwise. If the environment cannot install dependencies (network/toolchain), report BLOCKED with the error.
    phase: 1
  ```
- [INV-G2] Lint/format hooks pass.
  ```yaml
  verify:
    prompt: |
      In the worktree run: uv sync --dev && uv run prek run --all-files --hook-stage pre-merge-commit
      PASS only on exit 0. FAIL with the failing hooks and diffs otherwise. BLOCKED if tooling cannot be installed.
    phase: 1
  ```
- [INV-G3] Behavior contract: with pandas/numpy installed, every pre-existing public usage pattern still works and returns the same types — only warnings may be new. Spot-check at minimum: (a) `from hamilton import base; base.PandasDataFrameResult` resolves; (b) `import hamilton.base` emits no warning by itself; (c) legacy `driver.Driver({}, module)` with no adapter still returns a pandas DataFrame from `execute`; (d) `base.SimplePythonGraphAdapter(base.DictResult())` works as a Driver adapter.
  ```yaml
  verify:
    prompt: |
      Goal: prove the 1.9x changes are non-breaking when pandas is installed. In the worktree (env: uv sync --group test), write and run short python scripts covering at least: (a) from hamilton import base; base.PandasDataFrameResult is importable and usable as a result builder; (b) python -W error::DeprecationWarning -c "import hamilton.base, hamilton.driver" succeeds (shims must not warn at import time, only on attribute access); (c) a legacy driver.Driver({}, some_module) built WITHOUT any adapter executes a trivial pandas-series DAG and returns a pandas DataFrame (a DeprecationWarning is expected and acceptable here); (d) base.SimplePythonGraphAdapter(base.DictResult()) passed to a Driver returns a dict.
      PASS only if all four hold. FAIL with the violating snippet and its output otherwise.
    phase: 1
  ```
- [INV-G4] No module in the agreed cleanup set re-introduces a top-level (module-scope) `import pandas`/`import numpy`: `hamilton/driver.py`, `hamilton/base.py`, `hamilton/log_setup.py`, `hamilton/models.py`, `hamilton/io/utils.py`, `hamilton/function_modifiers/macros.py`, `hamilton/experimental/decorators/parameterize_frame.py`, `hamilton/data_quality/default_validators.py`. (`if TYPE_CHECKING:` imports are allowed.)
  ```yaml
  verify:
    prompt: |
      In the worktree, inspect the listed files: hamilton/driver.py, hamilton/base.py, hamilton/log_setup.py, hamilton/models.py, hamilton/io/utils.py, hamilton/function_modifiers/macros.py, hamilton/experimental/decorators/parameterize_frame.py, hamilton/data_quality/default_validators.py. PASS only if none contains a module-scope `import pandas`/`import numpy`/`from pandas ...`/`from numpy ...` executed at import time (imports inside `if TYPE_CHECKING:` blocks or inside function/method bodies are fine). FAIL listing file:line for each violation.
    phase: 1
  ```
- [INV-G5] Change-intent review clean.
  ```yaml
  verify:
    prompt: |
      Activate the manifest-dev:review-code skill with dimension=change-intent and review the full branch diff vs main in the worktree. Intent: the manifest at this file's path (1.9x non-breaking preparation for pandas/numpy removal). PASS only if no LOW-or-higher findings.
    phase: 2
  ```
- [INV-G6] Bug review clean.
  ```yaml
  verify:
    prompt: |
      Activate the manifest-dev:review-code skill with dimension=code-bugs and review the full branch diff vs main in the worktree. PASS only if no LOW-or-higher findings.
    phase: 2
  ```
- [INV-G7] Contracts review clean (public interfaces change shape here: relocations, shims, new warnings).
  ```yaml
  verify:
    prompt: |
      Activate the manifest-dev:review-code skill with dimension=contracts and review the full branch diff vs main in the worktree. Pay attention to: hamilton.base __getattr__ shims preserving the documented import surface; plugin modules (h_dask, h_narwhals, h_spark, h_vaex, h_polars) and async_driver still satisfying their contracts against relocated classes. PASS only if no LOW-or-higher findings.
    phase: 2
  ```
- [INV-G8] Type-safety review clean.
  ```yaml
  verify:
    prompt: |
      Activate the manifest-dev:review-code skill with dimension=type-safety and review the full branch diff vs main in the worktree. Note: TYPE_CHECKING-gated pandas imports were introduced; runtime type-hint introspection (typing.get_type_hints) must still resolve annotations that Hamilton inspects at runtime. PASS only if no LOW-or-higher findings.
    phase: 2
  ```
- [INV-G9] Advisory review dimensions clean: operational-readiness, code-design, code-maintainability, code-simplicity, code-testability, test-quality, docs, context-file-adherence.
  ```yaml
  verify:
    prompt: |
      For each dimension in [operational-readiness, code-design, code-maintainability, code-simplicity, code-testability, test-quality, docs, context-file-adherence]: activate the manifest-dev:review-code skill with that dimension and review the full branch diff vs main in the worktree. PASS only if no dimension reports a MEDIUM-or-higher finding. Report per-dimension results.
    phase: 2
  ```

*(Omitted from CODING base gates: prose-value — the only prose artifacts are changelog/docstring updates, covered by the docs dimension. Omitted FEATURE gates: requirements-traceability and behavior-completeness are covered by INV-G5 change-intent against this manifest; error-experience is encoded concretely as AC-2.3 and AC-4.2 warning-message checks.)*

## 4. Process Guidance

*Constraints on HOW to work. Not gates — guidance for the implementer.*

- [PG-1] Step-0 rule (user CLAUDE.md): D1's cleanup is its own commit, landed before any structural refactor of `base.py` or other >300 LOC files.
- [PG-2] One commit (or small coherent commit group) per deliverable; keep each commit reviewable (~≤5 files where feasible). Commit messages reference #918.
- [PG-3] Never commit `uv.lock` (currently untracked; the user has stated on apache/hamilton#1615 that adopting it needs a PPMC decision).
- [PG-4] All new files carry the Apache ASF license header used throughout the repo.
- [PG-5] Consumer sweep per user CLAUDE.md rule 10 when relocating/renaming: grep separately for direct references, type-level references, string literals, dynamic imports, re-exports, and test/mock usages of every moved name (`PandasDataFrameResult`, `StrictIndexTypePandasDataFrameResult`, `NumpyMatrixResult`, `SimplePythonDataFrameGraphAdapter`, plus validator class names).
- [PG-6] Run the existing test suite before modifying any test file (baseline awareness; prevents masking pre-existing failures).
- [PG-7] Deprecation warning texts must name: what is deprecated, the replacement (new import path or explicit argument), and "removed in Hamilton 2.0". Use `stacklevel` so the warning points at user code.
- [PG-8] No hard-wrapped prose in any new/edited `.md` files (user CLAUDE.md rule 11).
- [PG-9] Version bumps, release/changelog publication, and the devlist thread are out of scope — this manifest ends at a mergeable PR. Material devlist feedback triggers manifest amendment, not ad-hoc scope drift.
- [PG-10] Rollback strategy: the PR is revertible as a unit; no migrations or persisted state involved.

## 5. Known Assumptions

- [ASM-1] (auto) Shims warn on attribute access, not at `import hamilton.base` time. | Default: PEP 562 `__getattr__` + `__dir__`. | Impact if wrong: warning noise for every importer; encoded in INV-G3(b).
- [ASM-2] (auto) The old import path for relocated pandas validators (`hamilton.data_quality.default_validators.<Name>`) also gets a warning shim, consistent with `base`. | Default: same `__getattr__` + `RemovedInHamilton2Warning` pattern. | Impact if wrong: validators silently keep two permanent homes; amendment is one AC change.
- [ASM-3] (auto) Numpy result builder lands in a NEW `hamilton/plugins/h_numpy.py`; pandas builders/adapters land in the EXISTING `hamilton/plugins/h_pandas.py` (currently holds `with_columns`). | Impact if wrong: rename is mechanical.
- [ASM-4] (auto) The expiry gate is a unit test reading `hamilton.version.VERSION` (fails the suite at >=2.0 while any `RemovedInHamilton2Warning` usage remains), not a separate CI workflow. | Impact if wrong: a workflow job can be added later without rework.
- [ASM-5] (auto) Existing tests relying on the implicit pandas default are updated to pass explicit result builders (T-2) rather than blanket-suppressing the warning; `pytest.warns` is used where the warning itself is the subject under test.
- [ASM-6] (auto) The PR is opened non-draft against `apache/hamilton:main` from `origin` (`SummitSG-LLC/hamilton`) branch `2606/no_pandas`. The user may flip to draft pending devlist consensus via amendment.
- [ASM-7] (auto) The user's global "wait for explicit approval between phases" rule is satisfied by manifest-driven execution: /do's per-deliverable verification gates substitute for ad-hoc approval pauses, since the user explicitly delegated execution of this approved manifest.
- [ASM-8] `hamilton/telemetry.py` needs no changes (verified clean this session); the issue #918 text predates its cleanup.

## 6. Deliverables

*Ordered by execution order from Approach.*

### Deliverable 1: Step-0 safe cleanups (no behavior change)

Delete `np.seterr(divide="ignore", invalid="ignore")` and the numpy import from `hamilton/log_setup.py`. Remove module-scope pandas imports that exist only for annotations/docstrings/demo code by converting to `TYPE_CHECKING` or function-local imports in: `hamilton/driver.py` (used by docstrings + `__main__` demo only), `hamilton/function_modifiers/macros.py` (runtime uses at lines ~288/312 become local), `hamilton/models.py` (annotation-only), `hamilton/io/utils.py` (annotations + one `isinstance` in `get_sql_metadata` becomes guarded/local), `hamilton/experimental/decorators/parameterize_frame.py`.

**Acceptance Criteria:**
- [AC-1.1] The files listed in INV-G4 (except `base.py` and `default_validators.py`, handled in D3/D5) contain no module-scope pandas/numpy imports, and the full test suite still passes.
  ```yaml
  verify:
    prompt: |
      In the worktree: (1) confirm hamilton/log_setup.py no longer imports numpy nor calls np.seterr; (2) confirm hamilton/driver.py, hamilton/function_modifiers/macros.py, hamilton/models.py, hamilton/io/utils.py, hamilton/experimental/decorators/parameterize_frame.py have no module-scope pandas/numpy imports (TYPE_CHECKING blocks and function-local imports are fine); (3) run uv run pytest tests/ --ignore tests/integrations and confirm exit 0; (4) confirm @dynamic_transform and get_sql_metadata code paths still resolve pandas where they need it at runtime by locating the relocated local imports. PASS only if all four hold; FAIL with specifics.
    phase: 1
  ```
- [AC-1.2] Runtime type-hint introspection still works for every module converted to `TYPE_CHECKING` imports whose annotations Hamilton resolves at runtime (R-2): a test exercises `typing.get_type_hints` (or the equivalent Hamilton code path) against the affected annotations.
  ```yaml
  verify:
    prompt: |
      In the worktree, identify which modules in D1's scope had pandas imports moved under TYPE_CHECKING (at minimum check hamilton/models.py and hamilton/io/utils.py). For each, verify a test exists and passes that resolves the affected annotations at runtime (typing.get_type_hints or the Hamilton introspection path that consumes them), OR verify the annotations are demonstrably never runtime-resolved (cite the evidence). PASS only if every TYPE_CHECKING conversion is covered by one of the two. FAIL naming the uncovered module otherwise.
    phase: 1
  ```

### Deliverable 2: Central deprecation mechanism

New `hamilton/_deprecation.py`: `RemovedInHamilton2Warning(DeprecationWarning)` plus a `warn_deprecated(...)` helper (carries what/replacement/removal-version, sets `stacklevel`). Expiry-gate unit test: when `hamilton.version.VERSION >= (2, 0)`, any remaining in-repo usage of `RemovedInHamilton2Warning` fails the suite (test the gate logic itself by simulating the version). A suite-level guard bans raw `warnings.warn(..., DeprecationWarning)` for *new* Hamilton-2.0-related deprecations outside the helper (grep-based test scoped to avoid flagging pre-existing unrelated warns). Pytest configured so Hamilton's own internal code paths cannot trigger `RemovedInHamilton2Warning` (warning-as-error for the class, with `pytest.warns` opt-ins where the warning is the test subject).

**Acceptance Criteria:**
- [AC-2.1] The module, warning class, and helper exist with ASF header; helper emits `RemovedInHamilton2Warning` with actionable text; unit tests cover the helper.
  ```yaml
  verify:
    prompt: |
      In the worktree: confirm hamilton/_deprecation.py exists with the ASF license header, defines RemovedInHamilton2Warning subclassing DeprecationWarning and a warn helper that includes the deprecated name, its replacement, and the removal version ("2.0") in the message with an explicit stacklevel. Confirm unit tests exercise the helper and pass. PASS/FAIL with specifics.
    phase: 1
  ```
- [AC-2.2] The expiry gate works: a test demonstrates (by simulating VERSION >= (2,0)) that remaining `RemovedInHamilton2Warning` usages fail the suite, and the gate is inert at the current 1.x version.
  ```yaml
  verify:
    prompt: |
      In the worktree, locate the expiry-gate test for RemovedInHamilton2Warning. Verify: (a) at the repo's current VERSION the gate passes; (b) the test suite contains a check that simulates VERSION >= (2,0) (monkeypatch or parameterization) and asserts the gate would fail while usages remain; (c) the gate's detection enumerates usages mechanically (grep/import scan), not via a hand-maintained list. Run the relevant tests. PASS only if a, b, c all hold.
    phase: 1
  ```
- [AC-2.3] Error experience: every warning emitted through the helper in this branch points at user code (stacklevel) and names the concrete migration. Empirically check at least one emission site by triggering it and inspecting the warning's filename/lineno and message.
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test), write a small script that triggers at least one RemovedInHamilton2Warning from a simulated user call site (e.g. accessing hamilton.base.PandasDataFrameResult or constructing a legacy Driver without a result builder). Capture the warning with warnings.catch_warnings(record=True). PASS only if the warning's reported filename/line points at the calling script (not Hamilton internals) and the message names both the replacement and removal in 2.0. FAIL with the captured warning details otherwise.
    phase: 1
  ```

### Deliverable 3: Relocate pandas/numpy classes to plugins; shim `hamilton.base`; re-parent adapters

Move `PandasDataFrameResult`, `StrictIndexTypePandasDataFrameResult`, `SimplePythonDataFrameGraphAdapter` to `hamilton/plugins/h_pandas.py`; move `NumpyMatrixResult` to new `hamilton/plugins/h_numpy.py`. `hamilton.base` gains `__getattr__`/`__dir__` re-exporting the moved names with `RemovedInHamilton2Warning`. Re-parent `SimplePythonGraphAdapter` and `DefaultAdapter` onto `HamiltonGraphAdapter` (+ the static methods they used to inherit), resolving the TODO at base.py:443. Update all in-repo consumers (async_driver, plugins, tests, docs/docstrings) to the new import paths so the repo itself emits zero deprecation warnings.

**Acceptance Criteria:**
- [AC-3.1] New canonical paths work: `from hamilton.plugins.h_pandas import PandasDataFrameResult, StrictIndexTypePandasDataFrameResult, SimplePythonDataFrameGraphAdapter` and `from hamilton.plugins.h_numpy import NumpyMatrixResult` import cleanly and behave (build_result produces DataFrame/matrix as before — covered by relocated tests).
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test): import the four relocated classes from their new plugin paths and run the test files covering them. Confirm PandasDataFrameResult.build_result on two aligned pandas Series returns a DataFrame, and NumpyMatrixResult.build_result returns a numpy matrix. PASS/FAIL with output.
    phase: 1
  ```
- [AC-3.2] Old paths still work and warn exactly once per access pattern: `hamilton.base.<MovedName>` resolves to the same class object and emits `RemovedInHamilton2Warning`; `import hamilton.base` alone emits nothing; `dir(hamilton.base)` still lists the moved names.
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test), script-check: (a) python -W error::DeprecationWarning -c "import hamilton.base" exits 0; (b) accessing hamilton.base.PandasDataFrameResult, .StrictIndexTypePandasDataFrameResult, .SimplePythonDataFrameGraphAdapter, .NumpyMatrixResult each emits RemovedInHamilton2Warning and returns the identical class object (is-identity) as the plugin import; (c) all four names appear in dir(hamilton.base). PASS only if a, b, c hold for all names.
    phase: 1
  ```
- [AC-3.3] Re-parenting done: `SimplePythonGraphAdapter` and `DefaultAdapter` are no longer subclasses of `PandasDataFrameResult`/`SimplePythonDataFrameGraphAdapter`, retain their previous public behavior (check_input_type, check_node_type_equivalence, execute_node, build_result delegation, DictResult default), and the TODO comment at the old base.py:443 site is gone.
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test), script-check: issubclass(base.SimplePythonGraphAdapter, h_pandas.PandasDataFrameResult) is False; issubclass against HamiltonGraphAdapter is True; SimplePythonGraphAdapter() with no args still defaults to DictResult and its build_result returns a dict; check_input_type/check_node_type_equivalence/execute_node behave (run the existing adapter tests). Confirm the "TODO -- change this to extend the right class" comment no longer exists in hamilton/base.py. PASS/FAIL with specifics.
    phase: 1
  ```
- [AC-3.4] Zero internal deprecation-warning emissions: the repo's own code (hamilton/ and tests/, excluding tests that assert the warning via pytest.warns) triggers no `RemovedInHamilton2Warning` when the suite runs with that warning configured as error.
  ```yaml
  verify:
    prompt: |
      In the worktree, confirm pytest is configured (filterwarnings) to error on RemovedInHamilton2Warning, then run uv run pytest tests/ --ignore tests/integrations. PASS only if the suite passes with that configuration active and the only RemovedInHamilton2Warning occurrences in test code are inside pytest.warns/pytest.raises assertions. FAIL listing offending tests otherwise.
    phase: 1
  ```

### Deliverable 4: Deprecation warning on the implicit pandas result builder default

Legacy `Driver` construction (the `normalize_adapter_input` legacy path that appends `PandasDataFrameResult()`, driver.py:335) and `AsyncDriver`'s `result_builder or base.PandasDataFrameResult()` (async_driver.py:75) emit `RemovedInHamilton2Warning` when the default is exercised, telling users to pass a result builder explicitly and that the implicit default becomes `DictResult` in 2.0. Passing any explicit result builder emits nothing. Behavior is otherwise unchanged (still returns DataFrames). In-repo callers/tests updated to explicit builders per T-2/ASM-5.

**Acceptance Criteria:**
- [AC-4.1] Warning fires on both legacy implicit paths and not when explicit: covered by tests using `pytest.warns(RemovedInHamilton2Warning)` for `Driver({}, module)` and the AsyncDriver equivalent, and `warnings.simplefilter("error")`-style assertions for the explicit-builder cases.
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test), locate and run the tests covering the implicit-default deprecation in both Driver and AsyncDriver. Then independently script-check: constructing driver.Driver({}, m) with no adapter warns RemovedInHamilton2Warning whose message mentions DictResult and 2.0; constructing with an explicit result builder (e.g. base.DictResult() via SimplePythonGraphAdapter or as adapter) emits no RemovedInHamilton2Warning; execute() still returns a pandas DataFrame on the implicit path. PASS only if all hold for both Driver and AsyncDriver.
    phase: 1
  ```

### Deliverable 5: Split pandas validators with conditional registration

Pandas-coupled validator classes in `hamilton/data_quality/default_validators.py` (the `*PandasSeries` validators and numpy-dependent logic) move to a pandas-specific module; `AVAILABLE_DEFAULT_VALIDATORS` gains them via conditional registration mirroring `_append_pandera_to_default_validators` (default_validators.py:512). Old import paths shim+warn per ASM-2. `@check_output` resolution behavior is unchanged when pandas is installed.

**Acceptance Criteria:**
- [AC-5.1] With pandas installed, `resolve_default_validators` produces the same validator set as before the split for representative pandas and primitive argument combinations, and the relocated classes are importable from both new (silent) and old (warning) paths.
  ```yaml
  verify:
    prompt: |
      In the worktree (env: uv sync --group test): (1) run the data_quality test files; (2) script-check that AVAILABLE_DEFAULT_VALIDATORS contains the pandas-series validators (conditional registration fired, pandas being installed) plus the primitive validators; (3) check a representative pandas validator class imports from its new module without warning and from hamilton.data_quality.default_validators with RemovedInHamilton2Warning, yielding the identical class object; (4) confirm default_validators.py has no module-scope pandas/numpy import. PASS only if all four hold.
    phase: 1
  ```

### Deliverable 6: Upstream PR opened and driven to mergeable

Single PR from `origin` branch `2606/no_pandas` to `apache/hamilton:main`, titled and described against #918 (and noting the 2.0 ladder), with per-deliverable commit narrative. Description discloses the R-4 isinstance change and the public-code search result. PR body ends with the standard attribution footer.

**Acceptance Criteria:**
- [AC-6.1] PR lifecycle clean.
  ```yaml
  verify:
    prompt: |
      Activate the manifest-dev:check-pr skill.
      PR: the open pull request from SummitSG-LLC/hamilton branch 2606/no_pandas to apache/hamilton main (locate it via gh; if none exists yet, FAIL stating the PR has not been opened).
      Branch: 2606/no_pandas

      Steering: baseline. CI is GitHub Actions ("Unit Tests" workflow); treat integration-test flakiness on first run as retriggerable within the default cap. Do not merge; mergeable is terminal.
    phase: 3
  ```
~~~
